version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: math_fusion
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432" # Mapeo de puertos para acceder a la base de datos

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapeo de puertos para acceder a la API
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/math_fusion
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin